### ISSUE TITLE
Bug Report: Extra window when initializing program

### ISSUE THREAD

**Issue by wnmwnm** [EECS2311/EECS2311#109]
Reported by: Ning
 
Date: March 24th
 
Component: Notification
 
Release#: Itr2
 
Report Type: Coding
 
Can Reproduce: Yes
 
Severity: High
 
Priority: High
 
Problem summary: A new program window appears behind the Expiring Items Alert pop-up
 
Keywords: GUI, Notification
 
Problem description and how to reproduce it:
When the program initializes, the notification pop-up is shown in front of a second window instead of the main program window.
 
Suggested Fix:
Delete the code that initializes a second window.
 
Status: Open

**Comment by MichelCodes123** [comment]
Already fixed in latest
