### ISSUE TITLE
Bug report: Deleting an item in filter mode deletes wrong item

### ISSUE THREAD

**Issue by nina2dv** [EECS2311/EECS2311#113]
Reported by: Nina

Date reported: Mar 23, 2024

Program (or component/class) name: ItemsListView.java

Release number: Itr 2 (when filter feature came out)

```
Configuration(s):
    System Software Overview:
      System Version: macOS 14.2.1 (23C71)
      Kernel Version: Darwin 23.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

    Hardware Overview:
      Model Name: MacBook Air
      Chip: Apple M2
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.61.4
      OS Loader Version: 10151.61.4
```
Report type: coding

Can reproduce: yes

Severity: low (no crash)

Priority: Mid

Problem summary: Deleting an item with filter enabled deletes the wrong item.

Problem description and how to reproduce it:
1. Populate the database with DB_populate.sql after setting up (initialising the tables with DB_init.sql) the database. This acts as the user already has items and containers in the database.
2. Run the HomeView.java and click ok in the “Expiring Items Alert” notification to close that window
3. Click “View Containers” button to see available containers
4. Click on container “MainPantry”
5. Select “Fruit” in the top drop down and click “Find” button
6. Right click on the entry “Banana” and click “Delete Item”. Banana should not appear in the GUI table of the MainPantry container and will not exist in the database.
7. Remove the filter. “Banana” should still not be there.
8. Click the “back” button to go to see the list of available containers and click “MainPantry” again. “Banana” should still not be there.

Problem arises in step 6. Banana is still showing on the GUI and isn’t removed in the database. However, FruitLoops is removed instead since it is the 2nd row/entry in both the GUI table (before the filter) and was 2nd row in the database.

<img width="828" alt="image" src="https://github.com/EECS2311/EECS2311/assets/112736309/7bc15676-da9a-4461-a3b2-dac03e7ae764">

Keywords: Filter, Delete Item

Suggested fix: In ItemsListView.java, either do
1. Adjust right click listener to select current row on table (not the unfiltered table)
2. In filterTable method, can assign the filtered table to tableModel so that the right click delete item action listener can get the correct row when filtered.

Status: Open

Resolution: pending

**Comment by MichelCodes123** [comment]
Closed with the pull request. implemented suggestion 1.
