### ISSUE TITLE
Bug report: Storage tip of item in filter mode shows storage tip of wrong item

### ISSUE THREAD

**Issue by nina2dv** [EECS2311/EECS2311#116]
Reported by: Nina

Date reported: Mar 23, 2024

Program (or component/class) name: ItemsListView.java

Release number: Itr 2

Configuration(s):
```
    System Software Overview:
      System Version: macOS 14.2.1 (23C71)
      Kernel Version: Darwin 23.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

    Hardware Overview:
      Model Name: MacBook Air
      Chip: Apple M2
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.61.4
      OS Loader Version: 10151.61.4
```
Report type: coding

Can reproduce: yes

Severity: low (no crash)

Priority: Mid

Problem summary: Obtaining a storage tip of an item when filtered displays storage tip for a different item

Problem description and how to reproduce it:
1. Populate the database with DB_populate.sql after setting up (initialising the tables with DB_init.sql) the database. This acts as the user already has items and containers in the database.
2. Run the HomeView.java and click ok in the “Expiring Items Alert” notification to close that window
3. Click “View Containers” button to see available containers
4. Click on container “MainPantry”
5. Select “Fruit” in the top drop down and click “Find” button
6. Right click on the entry “Banana” and click “Storage Tip”. It should show a popup message, detailing on how to keep bananas’ shelf life longer. 

Similar to the delete item issue when in filter mode. Problem arises in step 6. Banana’s storage tip doesn’t show up (and it is in the database) but rather it selects FruitLoops’ storage tip, which has a no storage tip error message. 

<img width="789" alt="image" src="https://github.com/EECS2311/EECS2311/assets/112736309/93553353-9672-4644-8081-3acaba20cd91">

Keywords: Filter, Storage tip

Suggested fix: In ItemsListView.java, either do
1. Adjust right click listener to select current row on table (not the unfiltered table)
7. In filterTable method, can assign the filtered table to tableModel so that the right click storage tip action listener can get the correct row when filtered.

Status: Open

Resolution: pending

**Comment by MichelCodes123** [comment]
Closed with the pull request. implemented suggestion 1.
