### ISSUE TITLE
Bug Report: Recipe ingredients mismatch 2

### ISSUE THREAD

**Issue by EdisonnTran** [EECS2311/EECS2311#119]
Reported by: Edison

Date reported: Mar 24, 2024

Program (or component/class) name: domain.logic.recipe

Release: [Merge pull request](https://github.com/EECS2311/EECS2311/commit/88906cde0ccdb494666e45a584cccec8d4cad309) https://github.com/EECS2311/EECS2311/pull/102 [from EECS2311/FixNotif](https://github.com/EECS2311/EECS2311/commit/88906cde0ccdb494666e45a584cccec8d4cad309) [88906cd](https://github.com/EECS2311/EECS2311/commit/88906cde0ccdb494666e45a584cccec8d4cad309)

Can reproduce: yes

Severity: Low (no crash)

Priority: Low

Problem summary: Certain recipes do not properly include available and missing ingredients.

Problem description and how to reproduce it:

1. Select ‘ok’ on the expiration notification.
2. Create a new pantry by entering a name into the text box labelled “Pantry1” and then selecting ‘Create’.
a. Select ‘Yes’ to create the container.
3. Select ‘View Containers’ to navigate to the container screen.
a. Select the container that you created.
4. Now you are in the pantry screen. Create the following items to initialize some items to be able to test within the calendar view:
a. To create each item, take each of the values in the comma-separated list as separate inputs. The leftmost value goes into the “Item Name:” textbox, the middle value goes into the “Quantity:” textbox, and the rightmost value goes into the “Expiration Date (dd-MMM-yyyy):” textbox. Finally, select the “Add Item” button to add the new item.
i. Cookie, 3, 24-May-2024
ii. Steak, 9, 28-Jun-2024

The OREO Turkeys recipe listed “candy eyes” as an available ingredient despite not having anything related to candy in the container (as seen by the missing “candy corn” ingredient).

![image](https://github.com/EECS2311/EECS2311/assets/80595547/e4ca3275-9e83-4933-9c0b-ade9b40cbc2c)

Keywords: Recipe, Ingredients, Items, Container

Suggested fix: Refactor the filtering of ingredients available and missing ingredients to properly include ingredients with similar names.

Status: Open

Resolution: pending

**Comment by nina2dv** [comment]
This is the limitation of Spoonacular API: https://spoonacular.com/food-api/docs#Search-Recipes-by-Ingredients

It gets recipes and their needed ingredients from website/blog sources. The available and missing ingredients is determined by the API function itself. It would be available if the ingredients mentioned in the API query is related to the recipe's ingredients. It is also why it guesses "goat cheese" from "cheese" like in Bug Report: Recipe ingredients list mismatch #118. Sometimes, some of the available ingredients should be in missing ingredients and vice versa. But this ingredient sensitivity is not in my control. This recipe page would be treated more as recommendations.
