### ISSUE TITLE
Bug report: Lowercase food item does not show storage tip

### ISSUE THREAD

**Issue by nina2dv** [EECS2311/EECS2311#122]
Reported by: Nina

Date reported: Mar 24, 2024

Program (or component/class) name: ItemUtility.java and DB_init.sql 

Release number: Itr 2

Configuration(s):
```
    System Software Overview:
      System Version: macOS 14.2.1 (23C71)
      Kernel Version: Darwin 23.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

    Hardware Overview:
      Model Name: MacBook Air
      Chip: Apple M2
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.61.4
      OS Loader Version: 10151.61.4
```
Report type: coding

Can reproduce: yes

Severity: low

Priority: low

Problem summary: Lowercase food item does not show storage tip while its capitalized counterpart does.

Problem description and how to reproduce it:
1. Populate the database with DB_populate.sql after setting up (initialising the tables with DB_init.sql) the database. This acts as the user already has items and containers in the database.
2. Run the HomeView.java and click ok in the “Expiring Items Alert” notification to close that window
3. Create a new container
4. Click “View Containers” button to see available containers and click the container made in step 2
5. Add the following item names (with some quantity and expiry date):
  a. Capitalized food item like “Apple”
  b. All lowercase food item like “apple”
6. Right click on each of the new item entries and select storage tips.

“Apple” worked as expected. “apple” should display the storage tip like “Apple” but it acts as if there is no  “apple”  tip in the database. 

Keywords: Storage tip, Item name case sensitive

<img width="319" alt="image" src="https://github.com/EECS2311/EECS2311/assets/112736309/154da243-f947-41c8-a6b5-e428ef8cfab0">

<img width="572" alt="image" src="https://github.com/EECS2311/EECS2311/assets/112736309/7806e4c3-2758-4434-88bb-5e5bad462079">

Suggested fix: For case insensitivity, in db_init.sql, have all tip names in storage_tips table be lowercase and ItemUtility.retrieveStorageTip method do foodName.toLowercase() before passing into a DB method.

Status: Open

Resolution: pending

**Comment by EdisonnTran** [comment]
Fixed in [Merge pull request](https://github.com/EECS2311/EECS2311/commit/cd0d7330c76a715aa46b704e8864ced58304dde4) https://github.com/EECS2311/EECS2311/pull/169 [from EECS2311/allItems2](https://github.com/EECS2311/EECS2311/commit/cd0d7330c76a715aa46b704e8864ced58304dde4)
